version: "3.10"
services:
  api:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_user
      POSTGRES_DB: flask_app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", -U postgres]
      interval: 5s
      timeout: 5s
      retries: 5
