version: "3.10"
services:
  api:
    build:
      context: .
    ports:
      - "80:80"
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_user
      POSTGRES_DB: flask_app