version: "3.10"
services:
  api:
    image: azaiko/azaiko_skypro_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "80:80"
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", -U postgres]
      interval: 5s
      timeout: 5s
      retries: 5
