name: My first app deploy
on: [push]
jobs:
  build_and_push_project:
      runs-on: ubuntu-latest
      steps:
        - name: clone code
          uses: actions/checkout@v3
        - name: docker build
          run: docker build -t azaiko/azaiko_skypro_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
